version: '3.3'

services:
  nmpc:
    image: nmpc:humble
    user: root
    container_name: nmpc-humble
    build:
      context: ..
      dockerfile: ./dockerfiles/Dockerfile.windows
    volumes:
      - "../:/root/catkin_ws/src/nmpc/"
    privileged: True
    stdin_open: True
    # network_mode: host
    command: bash